# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ShVH3pWh
      POSTGRES_USER: blocks
      POSTGRES_DB: blocks
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    volumes:
      - /blocks_data:/var/lib/postgresql/data/pgdata
  app:
    build:
      context: app/
    ports:
      - 8005:8080
    depends_on:
      - "db"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080