store:
  hydra:
    ip_address: "192.168.98.18"
    username: "AIS_NET"
    password: "ooKegohshaih2AiGh7ietaiK"
    service: "hydra"
  local:
    ip_address: "db"
    username: "blocks"
    password: "ShVH3pWh"
    port: "5432"
    database: "blocks"
    driver: "postgres"
hydra_block_subscription_id: "608276901"
hydra_hash_sum_salt: "OTc1NjdkNzk2MWExM2YzYzA5MDljM2Nh"
server:
  ip_address: "localhost"
  port: "8080"